# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Network-Moya-RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Bidzaar-iOS
  pod 'Alamofire', '4.9.1'
  pod 'Moya', '13.0.1'
  pod 'Result', '4.1.0'
  pod 'RxSwift', '5.0.1'
  pod 'RxRelay', '5.0.1'
  pod 'RxCocoa', '5.0.1'

  target 'Network-Moya-RxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
